#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api.products.recommendations.get:
    path: /api/products/recommended/{locationCode}
    controller: App\Controller\GetRecommendedProductsController
